Rename and add new SimBench workflow jobs
Splitted the simbench_mvlv_urban_all_1 into two different cases

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -92,7 +92,7 @@ jobs:
             fi
           done
 
-  simbench_mvlv_urban_all_1:
+  simbench_mvlv_urban_all_1_sw:
     needs: simbench_mvlv_urban_all_0
     runs-on: ubuntu-latest
     timeout-minutes: 90
@@ -104,13 +104,41 @@ jobs:
       - name: Install dependencies
         run: |
           pip install pandapower simbench pvlib "oemof-demand>=0.2.2" workalendar
-      - name: Run SimBench MVLV urban all (1) (retry)
+      - name: Run SimBench MVLV urban all (1) sw (retry)
         run: |
           set -e
           max=3
           for i in $(seq 1 $max); do
             echo "Attempt $i of $max..."
-            python test_suite.py --only "MVLV-urban-all-1" && break
+            python test_suite.py --only "1-MVLV-urban-all-1-sw" && break
+            if [ "$i" -lt "$max" ]; then
+              echo "Retrying in 30s..."
+              sleep 30
+            else
+              echo "All attempts failed."
+              exit 1
+            fi
+          done
+
+  simbench_mvlv_urban_all_1_no_sw:
+    needs: simbench_mvlv_urban_all_1_sw
+    runs-on: ubuntu-latest
+    timeout-minutes: 90
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+        with:
+          python-version: "3.10"
+      - name: Install dependencies
+        run: |
+          pip install pandapower simbench pvlib "oemof-demand>=0.2.2" workalendar
+      - name: Run SimBench MVLV urban all (1) no_sw (retry)
+        run: |
+          set -e
+          max=3
+          for i in $(seq 1 $max); do
+            echo "Attempt $i of $max..."
+            python test_suite.py --only "1-MVLV-urban-all-1-no_sw" && break
             if [ "$i" -lt "$max" ]; then
               echo "Retrying in 30s..."
               sleep 30
@@ -121,7 +149,7 @@ jobs:
           done
 
   simbench_mvlv_urban_all_2:
-    needs: simbench_mvlv_urban_all_1
+    needs: simbench_mvlv_urban_all_1_no_sw
     runs-on: ubuntu-latest
     timeout-minutes: 90
     steps:
